### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by exchgr** [nickswalker/forecast.io-dashboard-widget#2]
This widget makes Dashboard use 40-50% CPU. I'm running a mid-2010 MacBook Pro with a 2.53 GHz Intel Core i5 (dual core with 4 threads). ![Activity Monitor](http://f.cl.ly/items/0k1M0E2Y2n0f0p3D0E3X/Screen%20Shot%202014-02-03%20at%2010.25.23%20AM.png)

**Comment by nickswalker** [comment]
The embed is using some pretty complex javascript/canvas tech to do the icon animations (http://blog.forecast.io/skycons-unobtrustive-animated-weather-icons/). You can observe about the same level of cpu usage from the examples they have. The problem is that dashboard keeps rendering things even when the user isn't in the dashboard, unlike Safari which is smart enough to stop rendering anything that is offscreen. I'm not sure if there are hooks to get notified when the user moves out of the dashboard, but that would be what I need to fix this. I'll look into it.

**Comment by neophit** [comment]
![screenshot 2014-02-16 12 41 50](https://f.cloud.github.com/assets/498432/2181304/324216da-974b-11e3-929a-a5f9adbab364.png)
